/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb68b",
        "secondary-container": "#fef3c7",
        "primary": "var(--primary-color, #1e40af)",
        "surface-tint": "var(--primary-color, #1e40af)",
        "primary-container": "var(--primary-color, #2563eb)",
        "outline-variant": "#c3c6d6",
        "on-tertiary-container": "#fffeff",
        "on-secondary-container": "#92400e",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#031942",
        "background": "#f8f9fa",
        "on-tertiary-fixed-variant": "#753400",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b4c6f8",
        "tertiary": "#d97706",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#dbeafe",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed-variant": "#344670",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "outline": "#737785",
        "on-tertiary-fixed": "#321300",
        "tertiary-fixed": "#fef3c7",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001946",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#b1c5ff",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b1c5ff",
        "tertiary-container": "#fbbf24",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4c5d89",
        "on-primary-container": "#ffffff",
        "on-surface-variant": "#424653",
        "on-primary-fixed-variant": "#1e3a8a",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#dbeafe",
        // legacy colors for compatibility
        "present": "#10B981",
        "absent": "#EF4444",
        "late": "#F59E0B",
        "excused": "#3B82F6",
      },
      borderRadius: {
        "lg": "1rem",
        "xl": "1.5rem",
      },
      fontFamily: {
        "lexend": ["Lexend", "sans-serif"],
        "headline": ["Lexend", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}