"use client";

import { useState } from "react";
import { Loader2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useClasses } from "@/lib/api/hooks/useClasses";
import { useAuthStore } from "@/app/(auth)/login/services/auth-store";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/lib/hooks/useToast";

export default function AddStudentDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { user } = useAuthStore();
  const schoolId = user?.schools?.[0]?.schoolId || user?.tenantId || "";
  const { data: classesResponse, isLoading } = useClasses(schoolId);
  const classes = Array.isArray(classesResponse) ? classesResponse : classesResponse?.data || [];
  const toast = useToast();

  const [formData, setFormData] = useState({
    fullName: "",
    classId: "",
  });
  const [isSaving, setIsSaving] = useState(false);

  const handleSave = async () => {
    if (!formData.fullName || !formData.classId) {
      toast.error.show("Please fill in all fields.");
      return;
    }

    setIsSaving(true);
    try {
      const payload = {
        ...formData,
        hasClassin: false, // Ensure classin integration is false as requested
        // studentCode will be generated by backend upon creation
      };

      console.log("Saving student payload:", payload);
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      toast.success.show("Student created successfully!");
      // Close dialog and reset form
      onOpenChange(false);
      setFormData({ fullName: "", classId: "" });
    } catch (error) {
      toast.error.show("Failed to create student.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Add New Student</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {isLoading ? (
            <>
              <Skeleton className="h-10 w-full rounded-md" />
              <Skeleton className="h-10 w-full rounded-md" />
            </>
          ) : (
            <>
              <Input
                placeholder="Full Name"
                value={formData.fullName}
                onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
              />

              <select
                value={formData.classId}
                onChange={(e) => setFormData({ ...formData, classId: e.target.value })}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <option value="" disabled>Select Class</option>
                {classes.map((cls: any) => (
                  <option key={cls.id} value={cls.id}>
                    {cls.name} {cls.section ? `(${cls.section})` : ""}
                  </option>
                ))}
              </select>
            </>
          )}
        </div>

        <DialogFooter>
          <Button
            onClick={handleSave}
            disabled={isLoading || isSaving}
            className="bg-primary hover:bg-primary/80 text-white w-full sm:w-auto flex items-center justify-center"
          >
            {isSaving && <Loader2 className="mr-2 animate-spin" size={16} />}
            Save Student
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
