import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes";
import { authenticateToken } from "../middleware/authMiddleware";
import { checkSubscription } from "../middleware/subscriptionMiddleware";
import notificationRoutes from "../modules/notification/notification.route";
import linkRoutes from "../modules/link/link.route";
import classRoutes from "../modules/class/class.route";
import academicRoutes from "../modules/academic/academic.route";
import adminRoutes from "../modules/admin/admin.route";
import sessionRoutes from "../modules/session/session.route";
import examRoutes from "../modules/exam/exam.route";
import schoolRoutes from "../modules/school/school.route";
import studentRoutes from "../modules/student/student.route";
import uploadRoutes from "../modules/upload/upload.route";
import gradeRoutes from "../modules/grade/grade.route";
import teacherRoutes from "../modules/teacher/teacher.route";
import paymentRoutes from "../modules/payment/payment.route";
import financeRoutes from "../modules/finance/finance.route";
import subscriptionRoutes from "../modules/subscription/subscription.route";
import platformRoutes from "../modules/platform";
import parentRoutes from "../modules/parent/parent.route";
import supportRoutes from "../modules/support/support.route";

const router = Router();

router.get("/health", (req, res) => res.status(200).send("API OK"));
router.use("/platform", platformRoutes);
router.use("/auth", authRoutes);
router.use("/notifications", notificationRoutes);
router.use("/subscription", subscriptionRoutes);
router.use("/links", authenticateToken, checkSubscription, linkRoutes);
router.use("/classes", authenticateToken, checkSubscription, classRoutes);
router.use("/academic", authenticateToken, checkSubscription, academicRoutes);
router.use("/admin", authenticateToken, adminRoutes);
router.use("/sessions", authenticateToken, checkSubscription, sessionRoutes);
router.use("/exams", authenticateToken, checkSubscription, examRoutes);
router.use("/schools", authenticateToken, schoolRoutes);
router.use("/students", authenticateToken, studentRoutes);
router.use("/upload", authenticateToken, uploadRoutes);
router.use("/grades", authenticateToken, checkSubscription, gradeRoutes);
router.use("/teacher", authenticateToken, teacherRoutes);
router.use("/parents", authenticateToken, parentRoutes);
router.use("/finance", financeRoutes);
router.use("/payment", paymentRoutes);
router.use("/support", supportRoutes);

export default router;
